# Generated by Django 4.2.1 on 2023-06-30 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='id_region',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='id_comuna',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='tipoProducto',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
