# Generated by Django 4.2.1 on 2023-06-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_remove_comuna_id_region_remove_direccion_id_comuna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Comuna')),
                ('comuna', models.CharField(max_length=255, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Region')),
                ('region', models.CharField(max_length=255, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='tipoProducto',
            fields=[
                ('id_tipoProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Tipo Producto')),
                ('tipo_producto', models.CharField(max_length=50, verbose_name='Tipo de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut Usuario')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres Usuario')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos Usuario')),
                ('fec_nac', models.DateField(verbose_name='Fecha Nacimiento Usuario')),
                ('telefono', models.IntegerField(verbose_name='Telefono Usuario')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email Usuario')),
                ('password', models.CharField(max_length=15, verbose_name='Password Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripcion del Producto')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('img', models.TextField(verbose_name='Nombre de la Imagen del Producto')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes del Producto')),
                ('stock', models.IntegerField(verbose_name='Stock del Producto')),
                ('tipo_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.tipoproducto', verbose_name='Tipo de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Productos')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.carrito', verbose_name='Id de Carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto', verbose_name='Productos de Carrito')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id direccion')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.comuna', verbose_name='Id comuna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario', verbose_name='Rut Usuario del Carrito')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.region', verbose_name='Id Region'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(through='administracion.ItemCarrito', to='administracion.producto', verbose_name='Productos de Carrito'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario', verbose_name='Rut Usuario del Carrito'),
        ),
    ]
