# Generated by Django 4.2.1 on 2023-06-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='img',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='static/core/img/logo.jpg', upload_to='static/adminstracion/img/productos/', verbose_name='Imagen del Producto'),
        ),
    ]
