# Generated by Django 4.2.1 on 2023-06-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_remove_producto_img_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='id_comuna',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id Comuna'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id_region',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id Region'),
        ),
    ]
