# Generated by Django 4.2.1 on 2023-07-01 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_alter_comuna_id_comuna_alter_region_id_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.comuna', verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='static/core/img/logo.jpg', upload_to='static/administracion/img/productos', verbose_name='Imagen del Producto'),
        ),
    ]
