# Generated by Django 4.2.1 on 2023-07-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alter_comuna_id_region_alter_direccion_id_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='static/core/img/logo.jpg', upload_to='media/administracion/img/productos', verbose_name='Imagen del Producto'),
        ),
    ]
