# Generated by Django 4.2.1 on 2023-07-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_alter_usuario_apellidos_alter_usuario_fec_nac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fec_nac',
            field=models.DateTimeField(verbose_name='Fecha Nacimiento'),
        ),
    ]
