# Generated by Django 4.2.1 on 2023-07-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_alter_usuario_fec_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='id_direccion',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id direccion'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario', verbose_name='Rut Usuario'),
        ),
    ]
