# Generated by Django 4.2.1 on 2023-06-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoProducto',
            fields=[
                ('id_tipoProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Tipo Producto')),
                ('tipo_producto', models.CharField(max_length=50, verbose_name='Tipo de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripcion del Producto')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('img', models.TextField(verbose_name='Nombre de la Imagen del Producto')),
                ('ingredientes', models.TextField(verbose_name='Ingredientes del Producto')),
                ('stock', models.IntegerField(verbose_name='Stock del Producto')),
                ('tipo_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoproducto', verbose_name='Tipo de Producto')),
            ],
        ),
    ]
